module.exports = [
  [1, {name: 'Battle axe', damage: '1d8', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Blowgun', damage: '--', quantity: 1, classes: ['Fighter', 'Ranger', 'Thief']}],
  [1, {name: 'Barbed Dart', damage: '1d3', quantity: 20, classes: ['Fighter', 'Ranger', 'Thief']}],
  [1, {name: 'Needle', damage: '1', quantity: 20, classes: ['Fighter', 'Ranger', 'Thief']}],
  [1, {name: 'Bow', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Composite long bow', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Composite short bow', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Flight arrow', damage: '1d6', quantity: 20, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Long bow', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Sheaf arrow', damage: '1d8', quantity: 20, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Short bow', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Club', damage: '1d6', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard', 'Cleric', 'Druid']}],
  [1, {name: 'Crossbow', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Hand quarrel', damage: '1d3', quantity: 20, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Hand crossbow', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Heavy quarrel', damage: '1d4+1', quantity: 20, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Heavy crossbow', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Light quarrel', damage: '1d4', quantity: 20, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Light crossbow', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Dagger or dirk', damage: '1d4', quantity: 10, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard', 'Mage', 'Illusionist']}],
  [1, {name: 'Dart', damage: '1d3', quantity: 20, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard', 'Mage', 'Illusionist']}],
  [1, {name: 'Footman\'s flail', damage: '1d6+1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Cleric']}],
  [1, {name: 'Footman\'s mace', damage: '1d6+1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Cleric']}],
  [1, {name: 'Footman\'s pick', damage: '1d6+1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Hand or throwing axe', damage: '1d6', quantity: 6, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Harpoon', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Horseman\'s flail', damage: '1d4+1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Cleric']}],
  [1, {name: 'Horseman\'s mace', damage: '1d6', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Cleric']}],
  [1, {name: 'Horseman\'s pick', damage: '1d4+1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Javelin', damage: '1d6', quantity: 6, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Knife', damage: '1d3', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard', 'Mage', 'Illusionist']}],
  [1, {name: 'Heavy horse lance', damage: '1d8+1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Light horse lance', damage: '1d6', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Jousting lance', damage: '1d3-1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Medium horse lance', damage: '1d6+1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Mancatcher', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Morning star', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Awl pike', damage: '1d6', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Bardiche', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Bec de corbin', damage: '1d8', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Bill-guisarme', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Fauchard', damage: '1d6', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Fauchard-fork', damage: '1d8', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Glaive 1', damage: '1d6', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Glaive-guisarme 1', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Guisarme', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Guisarme-voulge', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Halberd', damage: '1d10', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Hook fauchard', damage: '1d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Lucern hammer', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Cleric']}],
  [1, {name: 'Military fork', damage: '1d8', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Partisan', damage: '1d6', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Ranseur', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Spetum', damage: '1d6+1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Voulge', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Quarterstaff', damage: '1d6', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Cleric', 'Druid', 'Thief', 'Bard', 'Mage', 'Illusionist']}],
  [1, {name: 'Scourge', damage: '1d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Sickle', damage: '1d4+1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Sling', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Cleric', 'Druid', 'Thief', 'Bard', 'Mage', 'Illusionist']}],
  [1, {name: 'Sling bullet', damage: '1d4+1', quantity: 20, classes: ['Fighter', 'Paladin', 'Ranger', 'Cleric', 'Druid', 'Thief', 'Bard', 'Mage', 'Illusionist']}],
  [1, {name: 'Sling stone', damage: '1d4', quantity: 20, classes: ['Fighter', 'Paladin', 'Ranger', 'Cleric', 'Druid', 'Thief', 'Bard', 'Mage', 'Illusionist']}],
  [1, {name: 'Spear', damage: '1d6', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Staff sling', damage: '--', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Cleric', 'Druid', 'Thief', 'Bard', 'Mage', 'Illusionist']}],
  [1, {name: 'Bastard sword', damage: '1d8/2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Broad sword', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Khopesh', damage: '2d4', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Long sword', damage: '1d8', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Scimitar', damage: '1d8', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Druid']}],
  [1, {name: 'Short sword', damage: '1d6', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Thief', 'Bard']}],
  [1, {name: 'Two-handed sword', damage: '1d10', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Trident', damage: '1d6+1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
  [1, {name: 'Warhammer', damage: '1d4+1', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger', 'Cleric']}],
  [1, {name: 'Whip', damage: '1d2', quantity: 1, classes: ['Fighter', 'Paladin', 'Ranger']}],
];
